export const bill_categories = [
  { category_id: '1.0', category_name: 'Mobile Top Up' },
  { category_id: '2.0', category_name: 'Mobile PIN' },
  { category_id: '3.0', category_name: 'Bill Payment' },
  { category_id: '4.0', category_name: 'Mobile Data' },
  { category_id: '4.1', category_name: 'Mobile Data > Daily Bundles' },
  { category_id: '4.2', category_name: 'Mobile Data > 7-14 Day Bundles' },
  { category_id: '4.3', category_name: 'Mobile Data > Monthly Bundles' },
  {
    category_id: '4.4',
    category_name: 'Mobile Data > Extended Validity Bundles',
  },
  { category_id: '4.5', category_name: 'Mobile Data > Special Offers' },
  { category_id: '4.6', category_name: 'Mobile Data > SME Data Share Bundles' },
  { category_id: '5.0', category_name: 'Voice, Data & Combo Bundles' },
  { category_id: '6.0', category_name: 'Internet Services' },
  { category_id: '7.0', category_name: 'Cable TV' },
  { category_id: '8.0', category_name: 'Utilities' },
  { category_id: '8.1', category_name: 'Utilities > Electricity' },
  { category_id: '8.2', category_name: 'Utilities > Water' },
  { category_id: '8.3', category_name: 'Utilities > Transport & Toll Payment' },
  { category_id: '9.0', category_name: 'Betting' },
  { category_id: '10.0', category_name: 'Taxes' },
  { category_id: '10.1', category_name: 'Taxes > Federal' },
  { category_id: '10.2', category_name: 'Taxes > State' },
  { category_id: '11.0', category_name: 'Lifestyle' },
  { category_id: '11.1', category_name: 'Lifestyle > Education' },
  { category_id: '11.2', category_name: 'Lifestyle > Healthcare' },
  { category_id: '11.3', category_name: 'Lifestyle > Insurance' },
  { category_id: '12.0', category_name: 'Retail Gift Cards' },
  { category_id: '13.0', category_name: 'eVouchers' },
];

export const successful_account_lookup_test_ids = ['1954254407'];
